---
version: '3.1'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - net-mongodb-test

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - net-mongodb-test
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  mongo-client:
    image: mongoclient/mongoclient
    ports:
      - 8082:3000
    volumes:
      - mongo-client:/data/db
    networks:
      - net-mongodb-test

volumes:
  mongo-client:

networks:
  net-mongodb-test: